### ISSUE TITLE
vm-browserify accomplishes what evaljs attempts without issues in the browser

### ISSUE THREAD

**Issue by brucejo75** [marten-de-vries/evaljs#19]
Hi all,

I was looking for an eval solution that would be safe to use in my browser app.

I checked out [evaljs](https://github.com/marten-de-vries/evaljs) and [localeval](https://github.com/espadrine/localeval).  localeval provided a safer solution than evaljs and without acorn overhead.  Plus [localeval](https://github.com/espadrine/localeval) protected the global context.

> Try some of the [warnings](https://github.com/espadrine/localeval#warning) in localeval.  Scary stuff and evaljs fails these tests.

So I forked localeval and I made a change so that my context data would be retrievable from the eval.

I ran into some issues where the only explanation could have been that my `String.prototype.match` function was not working correctly, when I pulled localeval the issue went away.  So there may still be edge case bugs in localeval?

#### [vm-browserify](https://github.com/substack/vm-browserify)

In my investigations of my problem I looked into [vm-browserify.](https://github.com/substack/vm-browserify).  This provided the solution to the very same problem by running the eval in its own `vm`.  It looks like this solution is widely used and has millions of downloads.  For my case there are no side effects.

With this issue I am hoping I can help out anyone else looking for this solution.
[](https://github.com/espadrine/localeval/issues/8)

**Comment by hugs** [comment]
Thank you for the comment and research, @brucejo75. From a pure eval replacement point of view, you're correct, there are other simpler options out there that don't require a parser library dependency like acorn (or esprima). But there's more to eval.js, though, than just its ability to eval code. Since eval.js is a meta-circular interpreter (like Brendan Eich's Narcissus project), besides eval'ing code, you can also do all kinds of things with it, including creating an in-browser step debugger, or prototype new language features from within JavaScript itself. I'm closing this issue, but I agree with you, I hope both your comment (and mine) is helpful to people in the future.

**Comment by brucejo75** [comment]
Thanks for the comments @hugs.

Yes, for my application it is appropriate to pick simpler solutions.  But for other applications I can certainly see where a good parser is useful and necessary!
