### ISSUE TITLE
CallExpression  return exception

### ISSUE THREAD

**Issue by bplok20010** [marten-de-vries/evaljs#54]
```
function calc(a,b){
    return a+b
}
function main(a,b){
    return calc(a,b)
}
console.log(main(1,2)) //output: GeneratorFunctionPrototype [Generator] { _invoke: [Function: invoke] }
```

**Comment by marten-de-vries** [comment]
Thanks for your report. I cannot reproduce your problem, it's been years since I actively looked at the project, but copy/pasting your code at the end of 'theTest.js' (changing 1 & 2 to 1000 & 2000 to make the answer stand out more) makes 'node test.js' include '3000' in its output.

I think this project only supports, and was written in, ES5, so any message about generators surprises me. Are you sure it's a problem in eval.js?

**Comment by bplok20010** [comment]
Thank you for your reply
My example is not described correctly
But I solved it.
